id: I9B1FC348
legacy_id: null
ocr_import_info:
  bdrc_scan_id: W10305
  source: bdrc.io
  batch_id: batch003
  software_id: vision
  expected_default_language: bo
  ocr_info: {}
  op_import_options: {}
  op_import_version: 0.9.7
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-11-01T09:01:00.902964+00:00'
last_modified: '2022-11-01T09:01:00.902971+00:00'
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W10305
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW10305
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་ཆོས་གྲགས།
  languages:
  - bo
  author: ས་སྐྱ་ཡོངས་འཛིན་ངག་དབང་ཆོས་གྲགས།
statistics:
  ocr_word_mean_confidence_index: 0.9846095733740248
  ocr_word_median_confidence_index: 1.0
quality: null
bases:
  I2142:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2142
      total_pages: 624
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2142.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9846095733740248
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
